version: "3.7"
services:
  my-blog-test:
    image: kotlily/my-blog-react-express:latest
    expose:
      - 8000
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s
    environment:
      DB_CREDENTIALS_FILE: /run/secrets/db_secret
      FIREBASE_CREDENTIALS_FILE: /run/secrets/firebase_secret
    secrets:
      - firebase_secret
      - db_secret

  nginx:
    image: nginx:1.23.3
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - my-blog-test

secrets:
  firebase_secret:
    file: ./my-blog-backend/firebase-credentials.json
  db_secret:
    file: ./my-blog-backend/db-credentials.json 
