version: "3.7"
services:
  my-blog-test:
    image: my-blog-test-image:latest
    expose:
      - 8000
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
        window: 120s

  nginx:
    image: nginx:1.23.3
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - my-blog-test
