apiVersion: v1
kind: Service
metadata:
  name: my-blog
spec:
  type: LoadBalancer
  selector:
    app: my-blog
  ports:
  - port: 3333
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-blog
  template:
    metadata:
      labels:
        app: my-blog
    spec:
      containers:
      - name: my-blog
        image: kotlily/my-blog-react-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000
        env:
        - name: APP_PORT
          value: "8000"
        - name: MONGO_DB_NAME
          value: "react-blog-db"
        - name: MONGO_CONNECTION_STRING_PREFIX
          value: "mongodb+srv://"
        - name: MONGO_CONNECTION_STRING_OPTIONS
          value: "retryWrites=true&w=majority"
        # Secrets
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: k8s-my-blog-secrets
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: k8s-my-blog-secrets
              key: MONGO_PASSWORD
        - name: MONGO_CONNECTION_STRING_CLUSTER_URL
          valueFrom:
            secretKeyRef:
              name: k8s-my-blog-secrets
              key: MONGO_CONNECTION_STRING_CLUSTER_URL
        - name: FIREBASE_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: k8s-my-blog-secrets
              key: FIREBASE_CREDENTIALS
