# Secrets for the kubernetes cluster
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
type: Opaque
data:
  MONGO_USERNAME: {{ .Values.MONGO_USERNAME | b64enc }}
  MONGO_PASSWORD: {{ .Values.MONGO_PASSWORD | b64enc }}
  MONGO_CONNECTION_STRING_CLUSTER_URL: {{ .Values.MONGO_CONNECTION_STRING_CLUSTER_URL | b64enc }}
  FIREBASE_CREDENTIALS: {{ .Values.FIREBASE_CREDENTIALS }}
