name: "3-Deployment"
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Enter the target environment for the deployment
        options:
        - Staging
        - Production

env:
  #REGISTRY: docker.io
  #IMAGE_NAME: kotlily/my-blog-react-express
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  EKS_CLUSTER_NAME: t2micro-eks-cluster

jobs:
  deploy-eks:
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.URL }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    concurrency:
      group: deploy-${{ inputs.environment }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Use Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.3'
        id: install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Log into Container registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Deploy staging with push to ECR
        if: ${{ inputs.environment == 'Staging' }}
        id: push
        run: |
          echo "Deploying to Staging"
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:master ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}
          docker push ${{ secrets.AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ github.event.repository.name }}

      - name: Deploy production with aws CLI
        if: ${{ inputs.environment == 'Production' }}
        run: |
          echo "Deploying to Production"


      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Lint helm chart
        run: helm lint my-blog-helm

      - name: Template helm chart
        run: helm template my-blog-helm --namespace default --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --set image.tag=master \
               --set APP_PORT=${{ vars.APP_PORT }} \
               --set MONGO_DB_NAME=${{ vars.MONGO_DB_NAME }} \
               --set MONGO_CONNECTION_STRING_PREFIX=${{ vars.MONGO_CONNECTION_STRING_PREFIX }} \
               --set MONGO_CONNECTION_STRING_OPTIONS="${{ vars.MONGO_CONNECTION_STRING_OPTIONS }}" \
               --set MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
               --set MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
               --set MONGO_CONNECTION_STRING_CLUSTER_URL=${{ secrets.MONGO_CONNECTION_STRING_CLUSTER_URL }} \
               --set FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
               --set FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }} \
               --debug

      - name: Deploy to AWS EKS with Helm
        run: |
          helm upgrade --install ${{ github.event.repository.name }} my-blog-helm --namespace default --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --set image.tag=master \
               --set APP_PORT=${{ vars.APP_PORT }} \
               --set MONGO_DB_NAME=${{ vars.MONGO_DB_NAME }} \
               --set MONGO_CONNECTION_STRING_PREFIX=${{ vars.MONGO_CONNECTION_STRING_PREFIX }} \
               --set MONGO_CONNECTION_STRING_OPTIONS="${{ vars.MONGO_CONNECTION_STRING_OPTIONS }}" \
               --set MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
               --set MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
               --set MONGO_CONNECTION_STRING_CLUSTER_URL=${{ secrets.MONGO_CONNECTION_STRING_CLUSTER_URL }} \
               --set FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
               --set FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS }} \
               --debug --dry-run

      - name: Notify deployment status
        run: |
          echo "Deployment to ${{ inputs.environment }} completed"
